"""Update credits default to 3 for new users

Revision ID: ce0ae4893a2d
Revises: 7d1e1867e530
Create Date: 2025-12-22 21:42:55.443306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0ae4893a2d'
down_revision: Union[str, Sequence[str], None] = '7d1e1867e530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Change default value for credits column from 0 to 3
    op.alter_column('users', 'credits',
                    existing_type=sa.INTEGER(),
                    server_default='3',
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert default value for credits column from 3 to 0
    op.alter_column('users', 'credits',
                    existing_type=sa.INTEGER(),
                    server_default='0',
                    existing_nullable=False)
    # ### end Alembic commands ###
