"""Remove Stripe fields and add payment gateway fields

Revision ID: 7d1e1867e530
Revises: bc242a839afb
Create Date: 2025-12-22 21:18:07.076490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1e1867e530'
down_revision: Union[str, Sequence[str], None] = 'bc242a839afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new payment gateway columns
    op.add_column('users', sa.Column('credits', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('safepay_customer_id', sa.String(), nullable=True))
    op.create_unique_constraint('uq_users_safepay_customer_id', 'users', ['safepay_customer_id'])
    
    # Drop Stripe columns (if they exist)
    op.drop_constraint('users_stripe_subscription_id_key', 'users', type_='unique')
    op.drop_constraint('users_stripe_customer_id_key', 'users', type_='unique')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add Stripe columns
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.create_unique_constraint('users_stripe_customer_id_key', 'users', ['stripe_customer_id'])
    op.create_unique_constraint('users_stripe_subscription_id_key', 'users', ['stripe_subscription_id'])
    
    # Drop new payment gateway columns
    op.drop_constraint('uq_users_safepay_customer_id', 'users', type_='unique')
    op.drop_column('users', 'safepay_customer_id')
    op.drop_column('users', 'credits')
    # ### end Alembic commands ###
